### ISSUE TITLE
Feature request: add support to ommit --force

### ISSUE THREAD

**Issue by yoavkarako** [codefresh-contrib/cfstep-helm#17]
`helm upgrade` with the `--force` flag does a delete & install.
This is problematic when Kubernetes admission control denies the request, and results in a deleted deployment.

**Comment by ZahiC** [comment]
hey @RobinSoenen, we tried to change our configuration to 'promotion', and it seems to fail since the promotion action doesn't add the '--repo' param to the helm upgrade command. Hence, the helm upgrade command fails to download the chart:
`Error: failed to download "..." (hint: running "helm repo update" may help)`
Any advise?

**Comment by RobinSoenen** [comment]
You could ad  a CMD_PS parameter with the missing parameters

**Comment by yoavkarako** [comment]
@RobinSoenen That did it, thanks.
